# Generated by Django 3.2 on 2021-05-13 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_calls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calls',
            new_name='Call',
        ),
    ]
